// Generated by https://quicktype.io
export interface EQStatus {
  lifters:        { [key:string]: Lift};
  shuttles:       { [key: string]: Shuttle };
  system:         System;
  task_executors: { [key: string]: TaskExecutor };
}

export interface Shuttle {
  column:           number;
  is_auto:          boolean;
  is_disconnected:  number;
  is_error:         number;
  is_fully_charged: number;
  is_heartbroken:   number;
  is_idle:          number;
  is_loaded:        number;
  layer:            number;
  row:              number;
  task_id:          number;
  task_name:        number;
  task_param:       number;
}

export interface Lift {

  is_auto:          boolean;
  is_disconnected:  number;
  is_dislinked:     boolean;
  is_error:         number;
  is_heartbroken:   number;
  is_idle:          number;
  layer:            number;
  task_id:          number;
  task_name:        number;
  task_param:       number;
}

export interface System {
  lifters: SystemLifters;
  state:   number;
}

export interface SystemLifters {
  lifter_a0: boolean;
  lifter_a1: boolean;
  lifter_a2: boolean;
}

export interface TaskExecutor {
  coord:  number[];
  job_id: string;
  state:  number;
}
