// Generated by https://quicktype.io

export interface JobBill {
  total_page_count: number;
  bills:            Bill[];
}

export interface Bill {
  job_id:      string;
  job_type:    string;
  bin_id:      string;
  class_id:    string;
  priority:    string;
  from_coord:  string;
  from_action: string;
  to_coord:    string;
  to_action:   string;
  state:       string;
  user_id:     string;
  message:     string;
  update_date: string;
  create_date: string;
}
